##############################################
#   COMP90024 - Cluster and Cloud Computing
#   Project 2: Twitter Analysis
#   Author: Group 21
##############################################

---
- hosts: workers
  sudo: true
  vars:
    http_port: 80
  tasks:
  - name: update ubuntu
    command: sudo apt-get update
  - name: install couchdb
    apt: pkg=couchdb state=present
  - name: install curl
    apt: pkg=curl state=present
  - name: installing pip3
    apt: pkg=python3-pip state=present
  - name: installing python3 setuptools
    apt: pkg=python3-setuptools state=present
  - name: installing pip3
    command: easy_install3 pip
  - name: install couchdb for python3
    command: sudo pip3 install couchdb
  - name: installing tweepy
    command: pip3 install tweepy
  - name: installing NLTK
    command: sudo pip3 install nltk
  - name: installing goslate
    command: sudo pip install goslate
  - name: installing matplotlib
    apt: pkg=python3-matplotlib state=present
  - name: installing git
    apt: pkg=git state=present
  - name: Assures /home/ubuntu/cc_project dir exists
    file: path=/home/ubuntu/cc_project state=directory
  - name: download source code from repository
    git: repo=https://github.com/cristianmonterom/CloudComputingProjectTwo.git dest=/home/ubuntu/cc_project
  - name: setting permissions
    command: sudo chmod -R 777 /home/ubuntu/cc_project/
  - name: execution harvester in background
    command: python3 /home/ubuntu/cc_project/Harvesting/TweetsCity.py --server http://115.146.95.184:5984/ --db cloud_computing --consumer_key OvFt3ix2aummG26HtS8sT1MzU --consumer_secret 71tH27a3HljrW1cEOuoFZRPfmnZFqxhf4UXLI13rhgHfUA8mQ0 --token 128415623-tbIJqZujbYoYP4xsPleUWthHO7W6jnu5LscL6AAA --token_secret wSmbC1oRINjcnAvmCzbOABn8lsJ6GOxtZONGe6o80uEtr --db_user cc_users &
    async: 1000
    poll: 0
